### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by sciencectn** [konstantint/PyIntervalTree#5]
Insert this exact data and the last statement should crash it:

    t = IntervalTree()
    t.addi(-46.0, 31.0, 'test')
    t.addi(-20.0, 29.0, 'test')
    t.addi(1.0, 9.0, 'test')
    t.addi(-3.0, 6.0, 'test')
    t.removei(1.0, 9.0, 'test')
    t.removei(-20.0, 29.0, 'test')
    t.removei(-46.0, 31.0, 'test')

I'm using this library in a sweep line algorithm to detect rectangle overlaps. Using python 2.7.5.

**Comment by konstantint** [comment]
I fixed it, but now that Chaim-Leib has taken back the maintenance of this project, using ``intervaltree`` is the right way to do. I'll extract the genomic utility classes into a separate ``itervaltree-bio`` package now and leave this one for history.
